Create a function if car is blocked
Marius-P1/Need4Stek pull request #16
Opened 2023-04-30 16:37 UTC by Peralban

2023-04-30 16:44 UTC, Marius-P1 requested changes
Pas mal de truc à changer

2023-04-30 16:44 UTC, Marius-P1 commented on include/n4s_returns.h
> +    float old_speed;
Dans une nouvelle structure pas dans celle de thomas

2023-04-30 16:44 UTC, Marius-P1 commented on src/car_movements/car_is_blocked.c
> +
\n ?

2023-04-30 16:44 UTC, Marius-P1 commented on src/car_movements/car_is_blocked.c
> +    if (is_blocked == true)
pk revérifier comme ça ?

2023-04-30 16:44 UTC, Marius-P1 commented on src/car_movements/car_is_blocked.c
> +
vérification que lidar est bien de bonne taille pour éviter un segfault

2023-04-30 16:44 UTC, Marius-P1 commented on src/car_movements/car_is_blocked.c
> +int car_is_blocked(float *lidar)
Pk pas un bool ?

2023-04-30 16:44 UTC, Marius-P1 commented on include/n4s_returns.h
> +    float speed;
same

2023-04-30 16:44 UTC, Marius-P1 commented on include/n4s_returns.h
> +    float old_wheels_dir;
same

2023-04-30 16:44 UTC, Marius-P1 commented on include/n4s_returns.h
> +    float wheels_dir;
same

2023-04-30 16:46 UTC, Thomaltarix reviewed
Je suppose que c'est pour faire un demi tour ou un truc quand la voiture est bloquée mais est-ce qu'elle sera bloquée un jour la voiture :thinking: ?

2023-04-30 16:46 UTC, Thomaltarix commented on include/n4s_returns.h
Sert à quoi :thinking: ?

2023-04-30 16:46 UTC, Thomaltarix commented on src/car_movements/car_is_blocked.c
Ça se résume en "return (lidar[0] < 0.5 || lidar[31] < 0.5)" et ça sert à quoi aussi ?

2023-04-30 16:47 UTC, Marius-P1 commented on src/car_movements/car_is_blocked.c
Permet de reculer si jamais elle colle un mur ( nottament sur les maps avec des murs serré )

2023-04-30 17:05 UTC, Thomaltarix approved these changes
OK

2023-05-01 14:08 UTC, closed without merging

2023-05-01 14:08 UTC, Marius-P1 commented
Implémenter sans passer par cette branche